(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function m(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=aa(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;n(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&n(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ba(m(this))}})}return a});function ba(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function t(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:m(a)}}function ca(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.entries",function(a){return a?a:function(){return ca(this,function(b,c){return[b,c]})}});
r("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});var u=this||self;var da=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function w(a){w[" "](a);return a}w[" "]=function(){};var x={},y=null;
function ea(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}a=3;void 0===a&&(a=0);if(!y)for(y={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));x[e]=f;for(var g=0;g<f.length;g++){var k=f[g];void 0===y[k]&&(y[k]=g)}}a=x[a];c=[];for(d=0;d<b.length;d+=3){var l=b[d],h=(e=d+1<b.length)?b[d+1]:0;k=(f=d+2<b.length)?b[d+2]:0;g=l>>2;l=(l&3)<<4|h>>4;h=
(h&15)<<2|k>>6;k&=63;f||(k=64,e||(h=64));c.push(a[g],a[l],a[h]||"",a[k]||"")}return c.join("")};function z(a,b){var c=void 0===c?{}:c;this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c};var fa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function A(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{w(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}function B(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)}function la(a){var b=a.length;if(0==b)return 0;for(var c=305419896,d=0;d<b;d++)c^=(c<<5)+(c>>2)+a.charCodeAt(d)&4294967295;return 0<c?c:4294967296+c};function ma(a){u.google_image_requests||(u.google_image_requests=[]);var b=u.document.createElement("img");b.src=a;u.google_image_requests.push(b)};var C=document,na=window;function D(a){return!(!a||!a.call)&&"function"===typeof a}var E=!!window.google_async_iframe_id,F=E&&window.parent||window;function G(){if(E&&!A(F)){var a="."+C.domain;try{for(;2<a.split(".").length&&!A(F);)C.domain=a=a.substr(a.indexOf(".")+1),F=window.parent}catch(b){}A(F)||(F=window)}return F};var oa=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/;function H(a){a=a||I();for(var b=new K(u.location.href,!1),c=null,d=a.length-1,e=d;0<=e;--e){var f=a[e];!c&&oa.test(f.url)&&(c=f);if(f.url&&!f.l){b=f;break}}c=null;e=a.length&&a[d].url;0!=b.depth&&e&&(c=a[d]);return new pa(b,c)}
function I(a){var b=a||u,c=[],d=null;do{var e=b;if(A(e)){var f=e.location.href;d=e.document&&e.document.referrer||null}else f=d,d=null;c.push(new K(f||""));try{b=e.parent}catch(g){b=null}}while(b&&e!=b);e=0;for(b=c.length-1;e<=b;++e)c[e].depth=b-e;e=a||u;if(e.location&&e.location.ancestorOrigins&&e.location.ancestorOrigins.length==c.length-1)for(a=1;a<c.length;++a)b=c[a],b.url||(b.url=e.location.ancestorOrigins[a-1]||"",b.l=!0);return c}function pa(a,b){this.g=a;this.h=b}
function K(a,b){this.url=a;this.l=!!b;this.depth=null};function L(){this.i="&";this.h={};this.s=0;this.g=[]}function M(a,b){var c={};c[a]=b;return[c]}function N(a,b,c,d,e){var f=[];B(a,function(g,k){(g=qa(g,b,c,d,e))&&f.push(k+"="+g)});return f.join(b)}
function qa(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var f=[],g=0;g<a.length;g++)f.push(qa(a[g],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(N(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}
function ra(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;var d=sa(a)-c.length;if(0>d)return"";a.g.sort(function(q,v){return q-v});c=null;for(var e="",f=0;f<a.g.length;f++)for(var g=a.g[f],k=a.h[g],l=0;l<k.length;l++){if(!d){c=null==c?g:c;break}var h=N(k[l],a.i,",$");if(h){h=e+h;if(d>=h.length){d-=h.length;b+=h;e=a.i;break}c=null==c?g:c}}a="";null!=c&&(a=e+"trn="+c);return b+a}function sa(a){var b=1,c;for(c in a.h)b=c.length>b?c.length:b;return 3997-b-a.i.length-1};function ta(a,b,c,d,e){if((d?a.g:Math.random())<(e||.01))try{if(c instanceof L)var f=c;else f=new L,B(c,function(k,l){var h=f,q=h.s++;k=M(l,k);h.g.push(q);h.h[q]=k});var g=ra(f,a.h,"/pagead/gen_204?id="+b+"&");g&&ma(g)}catch(k){}};var O=null;function ua(){var a=u.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function va(){var a=void 0===a?u:a;return(a=a.performance)&&a.now?a.now():null};function wa(a,b){var c=va()||ua();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0};var P=u.performance,xa=!!(P&&P.mark&&P.measure&&P.clearMarks),Q=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a;if(a=xa){var b;if(null===O){O="";try{a="";try{a=u.top.location.hash}catch(c){a=u.location.hash}a&&(O=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=O;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});
function R(){var a=S;this.h=[];this.i=a||u;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.h=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=Q()||(null!=b?b:1>Math.random())}function ya(a){a&&P&&Q()&&(P.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),P.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}R.prototype.start=function(a,b){if(!this.g)return null;a=new wa(a,b);b="goog_"+a.label+"_"+a.uniqueId+"_start";P&&Q()&&P.mark(b);return a};
R.prototype.end=function(a){if(this.g&&"number"===typeof a.value){a.duration=(va()||ua())-a.value;var b="goog_"+a.label+"_"+a.uniqueId+"_end";P&&Q()&&P.mark(b);!this.g||2048<this.h.length||this.h.push(a)}};function za(){var a=T;this.i=U;this.u=!0;this.g=null;this.o=this.m;this.j=void 0===a?null:a;this.h=!1}
za.prototype.m=function(a,b,c,d,e){e=e||"jserror";try{var f=new L;f.g.push(1);f.h[1]=M("context",a);b.error&&b.meta&&b.id||(b=new z(b,{message:V(b)}));if(b.msg){var g=b.msg.substring(0,512);f.g.push(2);f.h[2]=M("msg",g)}var k=b.meta||{};if(this.g)try{this.g(k)}catch(J){}if(d)try{d(k)}catch(J){}b=[k];f.g.push(3);f.h[3]=b;var l=H();if(l.h){var h=l.h.url||"";f.g.push(4);f.h[4]=M("top",h)}var q={url:l.g.url||""};if(l.g.url){var v=l.g.url.match(fa),ha=v[1],ia=v[3],ja=v[4];h="";ha&&(h+=ha+":");ia&&(h+=
"//",h+=ia,ja&&(h+=":"+ja));var ka=h}else ka="";q=[q,{url:ka}];f.g.push(5);f.h[5]=q;ta(this.i,e,f,this.h,c)}catch(J){try{ta(this.i,e,{context:"ecmserr",rctx:a,msg:V(J),url:l&&l.g.url},this.h,c)}catch(Ka){}}return!0};
function V(a){var b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);for(var c;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(d){}}return b};var U,W,S=G(),T=new R;function Aa(){if(!S.google_measure_js_timing){var a=T;a.g=!1;a.h!=a.i.google_js_reporting_queue&&(Q()&&da(a.h,ya),a.h.length=0)}}U=new function(){var a=void 0===a?na:a;this.h="http:"===a.location.protocol?"http:":"https:";this.g=Math.random()};"number"!==typeof S.google_srt&&(S.google_srt=Math.random());var Ba=U,X=S.google_srt;0<=X&&1>=X&&(Ba.g=X);W=new za;W.g=function(){};W.h=!0;
if("complete"==S.document.readyState)Aa();else if(T.g){var Ca=function(){Aa()},Da=S;Da.addEventListener&&Da.addEventListener("load",Ca,!1)};function Ea(a){var b=a.indexOf("?");0<=b&&(a=a.substring(0,b));b=a.indexOf("#");0<=b&&(a=a.substring(0,b));return a}
function Fa(a){var b={},c=I(a);c=H(c);b.url=Ea(c.h?c.h.url:c.g.url);try{var d=a.history.length}catch(e){d=0}b.u_his=d;d=0;c=a;do{d++;try{c=c.parent!==c?c.parent:null}catch(e){c=null}}while(c&&20>=d);b.nhd=d;a.screen&&(b.u_w=a.screen.width,b.u_h=a.screen.height,b.u_aw=a.screen.availWidth,b.u_ah=a.screen.availHeight);a.navigator&&a.navigator.plugins&&(b.u_nplug=a.navigator.plugins.length);a=A(a.top)&&a.top.document?Ea(a.top.document.referrer):null;b.ref=a;return b}
function Ga(){var a=void 0===a?window:a;a=Fa(a);if(a=Object.entries(a).filter(function(b){b=t(b);b.next();return(b=b.next().value)||0===b}).map(function(b){var c=t(b);b=c.next().value;c=c.next().value;return encodeURIComponent(String(b))+"="+encodeURIComponent(String(c))}).join("&"))a=a+"&gdemsign="+String(la(a)),a=ea(a);return a};function Ha(){if(!u.gDemandSignals){u.gDemandSignals=Ga();var a=window,b=G();try{if(C.createEvent){var c=C.createEvent("CustomEvent");c.initCustomEvent("googledemandsignals",!0,!0,"");a.dispatchEvent(c)}else if(D(b.CustomEvent)){var d=new b.CustomEvent("googledemandsignals",{bubbles:!0,cancelable:!0,detail:""});a.dispatchEvent(d)}else if(D(b.Event)){var e=new Event("googledemandsignals",{bubbles:!0,cancelable:!0});a.dispatchEvent(e)}}catch(f){}}}var Y;
try{W.j&&W.j.g?(Y=W.j.start((478).toString(),3),Ha(),W.j.end(Y)):Ha()}catch(a){var Ia=W.u;try{ya(Y),Ia=W.o(478,new z(a,{message:V(a)}),void 0,void 0)}catch(b){W.m(217,b)}if(Ia){var Z,Ja;null==(Z=window.console)||null==(Ja=Z.error)||Ja.call(Z,a)}else throw a;};}).call(this);
